### ISSUE TITLE
implement security

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#56]
- acl see the changes in publishing tools, remove everything else, just this one config file should be enough

**Comment by Hamdy** [comment]
- [x] fix flatten https://github.com/crystaluniverse/publishtools/issues/59
- [x] fix config save https://github.com/crystaluniverse/publishtools/issues/60
- [x] fix shortname check https://github.com/crystaluniverse/publishtools/issues/61
- [x] rename circles to groups https://github.com/crystaluniverse/publishtools/issues/62
- [x] change nodeserver to work with new sites.json config https://github.com/crystaluniverse/publishtools/issues/63
- [x] 3bot connect + passwords should work side by side  https://github.com/crystaluniverse/publishtools/issues/64
- [x] Improved login and unauthoized pages with lovely style https://github.com/crystaluniverse/publishtools/issues/65
- [x] Test on staging  then deploy to production https://github.com/crystaluniverse/publishtools/issues/66
- [x] Make changes to publish command to be able to upload config file , update publish tools, .. https://github.com/crystaluniverse/publishtools/issues/67
