### ISSUE TITLE
Create a restful admin interface

### ISSUE THREAD

**Issue by Hamdy** [incubaid/crystaltools#69]
Create a restful admin Interface

- [ ] support global admin secret in sites.json https://github.com/crystaluniverse/publishtools/issues/70
- [x] admin restful Interface https://github.com/crystaluniverse/publishtools/issues/71
- [x] http method for adding ssh authorised key to server and enable ssh https://github.com/crystaluniverse/publishtools/issues/72
- [x] http method fir retrieving internal ip addr (useful to see how to connect over internal network)  https://github.com/crystaluniverse/publishtools/issues/73
- [x] http method  to use publishtools to pull all repo's (run as sub process) https://github.com/crystaluniverse/publishtools/issues/74
- [x] http methid to use publishtools to flatten and get content to digital twin server, reload DTWin Server https://github.com/crystaluniverse/publishtools/issues/75
- [x] http method to update publishtools https://github.com/crystaluniverse/publishtools/issues/76
- [ ] vlang based client using above rest interface with the secret  update publishtools https://github.com/crystaluniverse/publishtools/issues/77
- [ ] rest interface exposed on kubernetesip by using a defined dns hostname as specified during install https://github.com/crystaluniverse/publishtools/issues/78
